### ISSUE TITLE
Allow development mode when checking license

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-msteams-meetings#17]
Instead of allowing the plugin to run if an E20 license is enabled, it should also run if development mode is enabled.

The new check should make use https://github.com/mattermost/mattermost-plugin-api/pull/72 and be similar to https://github.com/mattermost/mattermost-plugin-incident-response/blob/c17fa2029a3f855b2a0f41510e4b3485a05744c5/server/plugin.go#L57-L59.

**Comment by cjmartian** [comment]
Hey @hanzei, 

I'd like to take this one.

If I'm understanding this correctly, you want this plugin to run if an E20 license is enabled or if the config states it is being ran in development mode?

I'm looking at https://github.com/mattermost/mattermost-plugin-api/pull/72 and it seems like the function that is currently being called does just that. 
https://github.com/mattermost/mattermost-plugin-api/pull/72/files#diff-db2f4f67c054c0fe58427305559af1f5R21-R42

I think I'm missing something perhaps, let me know!

**Comment by hanzei** [comment]
Exactly @cjmartian. https://github.com/mattermost/mattermost-plugin-api/pull/72 is just a library function. This ticket is about adopting the library function for this PR.

Does this make the ticket more clear?

**Comment by cjmartian** [comment]
I believe so @hanzei I'll set up a dev environment and see if I can't add these changes. If I have more questions, would you mind if I ping you again here?

Thank you for the explanation

**Comment by hanzei** [comment]
Sure, ping me :+1: Also feel free to PM me on the [Mattermost Community Server](https://community.mattermost.com).

**Comment by hanzei** [comment]
If you found this ticket interesting, you might also want to take a look at https://github.com/mattermost/mattermost-plugin-mscalendar/issues/194
