### ISSUE TITLE
Release v0.1.0

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-msteams-meetings#21]
As Beta to the Marketplace

- [x] https://github.com/mattermost/mattermost-plugin-msteams-meetings/pull/15
- [x] https://github.com/mattermost/mattermost-plugin-msteams-meetings/pull/19
- [x] https://github.com/mattermost/mattermost-plugin-msteams-meetings/pull/20
- [x] https://github.com/mattermost/mattermost-plugin-msteams-meetings/pull/26
- [x] https://github.com/mattermost/mattermost-plugin-msteams-meetings/pull/27

**Comment by hanzei** [comment]
@larkox Are we ready to cut a release branch now?

**Comment by larkox** [comment]
We would need @DHaussermann 's testing to be done first.

**Comment by hanzei** [comment]
Usually Release testing is done in the version bump PR. Can we do the same for this plugin?
