### ISSUE TITLE
Warn before posting a meeting in a populated channel

### ISSUE THREAD

**Issue by larkox** [mattermost/mattermost-plugin-msteams-meetings#22]
Should we warn the user before posting a meeting in a populated channel? What can be considered a "populated channel"? Any public channel?
Should we add some setting to avoid posting meetings on public channels?

cc @aaronrothschild

**Comment by aaronrothschild** [comment]
@larkox Is the meeting ID generated dynamically for each meeting or is it re-used?

**Comment by larkox** [comment]
If I remember correctly, a new ID is created for each new meeting.

**Comment by aaronrothschild** [comment]
Gotcha if the user can delete the message themselves, and the meeting ID is unique (not my personal meeting ID etc.) then I think the risk of accieentally posting in a public forum isn't that great (compared to zoom using my PMI) IMO.  

However, if this is about adding like 1000 people to a MS Teams call and then "ringing them" to notify them all about the meeting...that would be bad ;) but I know we still don't know the status of the "ringing function".

**Comment by larkox** [comment]
Also, for that case, we are not "adding all the people to the call" on public nor private channels. Only Direct Messages and Group messages.

**Comment by catalintomai** [comment]
Please createhelp-wanted ticket out of.

**Comment by larkox** [comment]
HW Ticket created: https://github.com/mattermost/mattermost-plugin-msteams-meetings/issues/29
