### ISSUE TITLE
Improve Installation & Configuration Docs

### ISSUE THREAD

**Issue by icelander** [mattermost/mattermost-plugin-msteams-meetings#45]
Make sure that numbered lists don't reset to `1.` after screenshots

Make sure images render correctly, e.g. `<img width="500 src="https://user-images.githubusercontent.com/6913320/76348298-55cd4880-62de-11ea-8e0e-4ace3a8f8fcb.png"/>`

Make it clear whether you need an Office365 subscription and/or account for Teams to work

Make sure screenshots of permissions show the minimum necessary permissions for the teams plugin to work and also list these permissions as text

Add note that you must be an admin to grant admin consent, and that if the option is greyed out you need to to contact your Azure administrator

**Comment by justinegeffen** [comment]
Thanks, @icelander! This is super helpful.

**Comment by hanzei** [comment]
@icelander Is this issue still valid now that the docs are in  [GitBook](https://mattermost.gitbook.io/microsoft-teams-pluginmsteams-meetings-plugin/)?
