### ISSUE TITLE
2nd time when user Disconnect the account then Validation Message Should be Proper.

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost-plugin-msteams-meetings#65]
Currently when The User Disconnect account 2nd time then user is getting validation as **"Failed to disconnect the user, err=must connect user account to Microsoft first"** but we should not show text as **err=**. 
             
simple Fix Should be just remove that text and The validation should be **Failed to disconnect the user, must connect user account to Microsoft first**

**Comment by dipak-demansol** [comment]
Pls assign This to me.

**Comment by dipak-demansol** [comment]
before, when then user disconnect the account again then user was getting this validation message 
![image](https://user-images.githubusercontent.com/89907719/161909656-cfbe1eb0-2cf8-483c-a9f2-5d47af7a127d.png)

and now From that message i removed **err=** and the message looks like this
![image](https://user-images.githubusercontent.com/89907719/161909946-87f27168-4e4b-485d-aa0c-c79ea1680765.png)

@cwarnermm i did the changes on that message by removing that **err=** but still is there any improvement  we can do? or that validation message is proper?

**Comment by cwarnermm** [comment]
Thanks, @dipak-demansol, for reaching out. I appreciate it. 

Let's update this message to: "Failed to disconnect user. Connect the user account to Microsoft Teams, then try again."

**Comment by dipak-demansol** [comment]
> Thanks, @dipak-demansol, for reaching out. I appreciate it.
> 
> Let's update this message to: "Failed to disconnect user. Connect the user account to Microsoft Teams, then try again."

Thank you for the reply, i have some thought about that message.
                :-  i suggest we should remove that "then try again" text because user is already not connected and as per this message we're saying that connect account then try again to disconnect, i think our validation message focus should be on to tell user to connect account not to try again for disconnection.  
               if you still Confirm that we should use the validation message that you provided then pls let me know, ill use that.

**Comment by dipak-demansol** [comment]
> > Thanks, @dipak-demansol, for reaching out. I appreciate it.
> > Let's update this message to: "Failed to disconnect user. Connect the user account to Microsoft Teams, then try again."
> 
> Thank you for the reply, i have some thought about that message. :- i suggest we should remove that "then try again" text because user is already not connected and as per this message we're saying that connect account then try again to disconnect, i think our validation message focus should be on to tell user to connect account not to try again for disconnection. if you still Confirm that we should use the validation message that you provided then pls let me know, ill use that.

@cwarnermm

**Comment by dipak-demansol** [comment]
> Thanks, @dipak-demansol! Can you help me understand the context of this message, please? What is the user doing when this message appears?
> 
> * who is doing the disconnecting?
> * are they disconnecting themselves or someone else?
> * what are they disconnecting someone from exactly?
> 
> Thanks!

@cwarnermm 
:- who is doing the disconnecting? 
A :- consider i'm the user and i'm disconnecting my self

are they disconnecting themselves or someone else?
A :- themselves

what are they disconnecting someone from exactly?
A :- they Connected with msteem plugin and User Disconnected themselves and user again using the same disconnect command to disconnect  themselves so as per the old validation "we're telling to user that disconnect command failed, first connect the account to microsoft"

**Comment by cwarnermm** [comment]
Thank you, @dipak-demansol! This context is very helpful. I agree with your assessment that we can remove the "try again" text. Let's go with your recommendation of "Failed to disconnect user. Connect the user account to Microsoft Teams."
