### ISSUE TITLE
slash Command improvement 

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost-plugin-msteams-meetings#67]
When i Use **/mstmeetings help xyz** then its ignore the extra parameter and give me the right output but when i use **/mstmeetings start xyz** or **/mstmeetings disconnect xyz** then it gives me the validation as **"Too many parameters."** but i **expect start & disconnect should work same as help**, it should not give the validation, it should ignore The Extra parameter.

**Comment by catalintomai** [comment]
Decided not to change existing behavior.
