### ISSUE TITLE
MS Teams Calling shows plugin ID as App Bar tooltip

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-msteams-meetings#72]
When MS Teams is moved to the app bar, the tooltip seems to change. The plugin now shows the plugin ID instead of the previous tooltip about starting a meeting. 

Short of the App Bar, I see so other change causing the tooltip to change. Likely this was missed in testing when MS teamms registered a new icon in the App Bar
![image](https://user-images.githubusercontent.com/35588783/171490648-942f9b85-f690-4924-80c8-be1f008971a8.png)

**Note**: Not sure on the solution here as I believe the more permanent place for this is in the new Calls componenet

**Comment by catalintomai** [comment]
@DHaussermann , Michael says he fixed it in the plugin framework - just needs to be validated.
