### ISSUE TITLE
Installation docs still lists E20 license as a requirement

### ISSUE THREAD

**Issue by Schleuse** [mattermost/mattermost-plugin-msteams-meetings#85]
This plugin seems to no longer require an E20 license (#80) to function :tada:, but the [installation docs](https://github.com/mattermost/mattermost-plugin-msteams-meetings/blob/master/docs/setup/installation-and-configuration.md) still mentions this as a requirement. Can this requirement be removed from the docs?

**Comment by hanzei** [comment]
@javaguirre Would you mind doing the cleanup?

**Comment by hanzei** [comment]
Good catch @Schleuse :+1: Are you interested in updating the docs?

**Comment by Schleuse** [comment]
@hanzei I've opened a pull request which updates the requirement in the docs
